### PR TITLE
[xcpmd] Turn off Wno-unused and cleanup unused stuffs.

### PR DESCRIPTION
**Pull request by rossphilipson**
OXT-441

Signed-off-by: Ross Philipson philipsonr@ainfosec.com

### CODE REVIEW

**Comment by eric-ch** [comment]
LGTM, +1. I have not tested yet though.

**Comment by jean-edouard** [comment]
LGTM, I don't think this needs much testing. If it compiles it should be good to go.

**Comment by rossphilipson** [comment]
Did a build w/ it over the weekend:
http://158.69.127.133:8020/builders/openxt-custom/builds/22

The first attempt failed because my xenclient-oe was out of date.

**Comment by jean-edouard** [comment]
Green! \o/
Will merge soon.

**Pull request merged**
