### PR TITLE
xcpmd/audio: refresh autotools configurations

### PR DESCRIPTION
**Pull request by eric-ch**
- Remove the constructs carried over from templated configurations that no longer apply or serve a purpose.
- Turn `-Werror` in audio-helper while at it and fix the warnings.
- Add relevant `.gitignore` where needed.

### CODE REVIEW

**Comment by eric-ch** [comment]
v2:
- Mentioned .gittignore additions in commit messages;
- Attend warnings in a more appropriate fashion.

**Review by jandryuk — APPROVED** [review]
Looks good.  Thanks!

**Review by dpsmith — APPROVED** [review]

**Comment by eric-ch** [comment]
[Build](https://openxt.ainfosec.com/buildbot/#/builders/10/builds/19): [mcq-19](https://openxt.ainfosec.com/OpenXT/auto/master/master-custom-quick/19/)

**Comment by jandryuk** [comment]
Will merge soon.

**Pull request merged**
