### PR TITLE
Updates after Linux Argo header changes: OXT-1694

### PR DESCRIPTION
**Pull request by dozylynx**
This PR works in conjuction with changes in xenclient-oe and linux-xen-argo repositories for OXT-1694.

- An include for `<stdbool.h>` is needed since it is no longer provided via transitivity
- `xen_argo_ring_t` is no longer visible to Linux userspace so the headroom left for ring header use is calculated without it. The method used here should be revisited with the interface provided to userspace by new Linux Argo driver. The value `(8 * XEN_ARGO_ROUNDUP(1))` leaves 3 slots of headroom over the prior value as a precaution in the absence of a method for sizing provided by the driver.

Signed-off-by: Christopher Clark <christopher.clark6@baesystems.com>

### CODE REVIEW

**Review by jandryuk — COMMENTED** [review]
There are too many argo.h files and I get confused.  `xen/argo.h` defines `xen_argo_ring_t` but that isn't available and only `linux/argo.h` is available?

Isn't 8 wrong?  Looks like sizeof(xen_argo_ring_t) is 64.  Also, we have to programs here wanting to use the define, so I think it may deserve promotion to a public header.  It doesn't have to be xen_argo_ring_t. but just a `#define ARGO_RING_OVERHEAD X` and ideally a build time assert that `ARGO_RING_OVERHEAD == sizeof(xen_argo_ring_t)`.

If you don't want to do that, I think the '8' below deserves a comment.  And/or make 8 into a `#define` with a comment.

It's a little unfriendly that all callers are expected to subtract the ring overhead.  It'd be an API change, but you could have linux or xen subtract off the header instead.  I'm not looking at the code, but a ring has to be at least a page, so there would always be space.

**Comment by dozylynx** [comment]
- given the similar purpose and content between `<linux/argo.h>` and `<xen/argo.h>` I think the similar names in this specific case are helpful and the scoping of `<linux/` or `<xen/` is the right way to distinguish them. Agree on other "argo.h"s and I removed one with these PRs.

- Agree with adding `ARGO_RING_OVERHEAD` to `<linux/argo.h>`.
Will need to consider where exactly to add the build-time assert on the correctness of the size wrt `sizeof(xen_argo_ring_t)`, given that that type definition is not available via `<linux/argo.h>`.

- Also agree that it is unfriendly to have all callers subtract the ring overhead; will leave that API change for inclusion with the larger Linux driver project though.

My work on this is on hold for a little while.

**Comment by jandryuk** [comment]
I didn't fully explain my multiple argo.h comment.
linux-xen-argo.git
dafba35cb941bbcf385dba7da622e7756b4c5a80  ./vsock-argo/module/include/xen/argo.h
41e2f707156476c92dea24915f49673388bee218  ./argo-linux/include/argo.h
65bef8b8aff5c83a20b51b8320b1d2fbdaefb7c1  ./argo-linux/include/xen/argo.h
xen.git
d51dff4d3d5fce8d33ba2494da86b7d927ddb0f5  ./xen/include/xen/argo.h
422b559515a23cd9b138eb0a0e1096d01aebce2b  ./xen/include/public/argo.h
83333e0fcbcaf0b9718221fe6302fc229f85826b  ./tools/firmware/xen-dir/xen-root/xen/include/compat/.xlat/argo.h
5d8f5e29ca744b83abc09635576d16c962ed80f4  ./tools/firmware/xen-dir/xen-root/xen/include/compat/argo.h
(xen.git actually has some duplicate copies)

There are 3 different xen/argo.h files, so it's hard to know which one is the correct one.

**Comment by dozylynx** [comment]
PR refreshed.
The requested compile-time check on ARGO_RING_OVERHEAD is included in the corresponding PR 7 on linux-xen-argo.

**Comment by dozylynx** [comment]
The multiple argo.h header issue has not been addressed in this latest push but I will look into it; haven't yet determined whether to include resolving that in this work for OXT-1694.

**Review by dpsmith — APPROVED** [review]
Reviewed-by: Daniel P. Smith <dpsmith@apertussolutions.com>

**Review by eric-ch — APPROVED** [review]

**Review by jandryuk — APPROVED** [review]

**Comment by dozylynx** [comment]
I have spent a bit of time looking into the multiple header issue since my last update on this, but have since been busy with other tasks, so have not got a resolution for it yet. I have limited time available this week as I'm attending a conference, but would like to unblock progress on this, so will take a look. I think the best course may be to move the multiple-header issue to out of scope for this PR and work on it separately.

**Comment by jandryuk** [comment]
Yes, don't worry about the header naming since, like you say, it is out-of-scope.

**Comment by eric-ch** [comment]
Will merge soon.

**Pull request merged**
