### PR TITLE
[OXT-561] Fix crash at first boot.

### PR DESCRIPTION
**Pull request by jctemkin**
If the DB isn't up when XCPMD tries to read from it, NULLs are returned. Turns out it's a bad idea to blindly dereference them.

Also, a few memory leak cleanups while I'm poking around in there.

### CODE REVIEW

**Comment by jean-edouard** [comment]
This failed to build...
See http://158.69.127.133:8020/builders/openxt-custom/builds/69/steps/Build/logs/stdio

**Comment by jctemkin** [comment]
Oof, that's embarrassing. I'm running a full build of master right now so I can test properly and avoid this in the future. I'll check in again shortly.

**Comment by jean-edouard** [comment]
ping

**Comment by jctemkin** [comment]
Fixed.

**Comment by jean-edouard** [comment]
Built here: http://158.69.127.133:8020/builders/openxt-custom/builds/72
+1, fixed the segfault on my laptop

**Comment by jean-edouard** [comment]
Will merge soon.

**Pull request merged**
