### PR TITLE
Implement modular and policy-driven power management.

### PR DESCRIPTION
**Pull request by jctemkin**
This PR introduces a policy system to XCPMD. It's based on rules--when a set of conditions occur, perform an action, or series of actions, and when the conditions are no longer true, perform a set of "undo" actions. This policy can be written in a file, loaded from the DB, or added on-the-fly over DBus. It's designed to be flexible and robust without being overly complicated.

The conditions that can be checked and the actions that can be taken are implemented in their own self-contained modules. The module loading system provides a straightforward, regular interface for inserting new conditions and actions, should anyone want to extend on the capabilities provided.

I understand that the diff is extensive, but I believe this will greatly augment OpenXT's power management capabilities. I'd much appreciate any input. Thanks for reading!

Depends on [idl PR9](https://github.com/OpenXT/idl/pull/9).

### CODE REVIEW

**Comment by stacktrust** [comment]
It would be helpful to have a JIRA ticket and/or wiki page which documents the design of this new feature, has examples of policies supported by the current modules, and instructions for adding new modules/policies.  It would also be helpful to compare the proposed API with those of existing OS platforms or standards, e.g. DMTF policies for managing hardware or virtual platforms.

**Comment by pearsonk** [comment]
I agree with @transpute in that such a feature should be documented with regards to its design but also the means to configure and use this from an end-user (non-developer Admin) perspective.

**Comment by jctemkin** [comment]
While the documentation ultimately belongs on a Confluence page, it seems a bit premature to post everything there before this PR is even approved. I've created a [Jira ticket](https://openxt.atlassian.net/browse/OXT-384) and attached a PDF providing fairly detailed documentation.

**Comment by rossphilipson** [comment]
I am starting to review and test this new feature. I know @transpute and @pearsonk made some comments on documenting this feature. @jctemkin did a nice write-up and attached it to the ticket. Does this satisfy what was requested? That write-up should probably make its way to Confluence too.

**Comment by rossphilipson** [comment]
Build failed. Looks like configure.in is missing LT_INIT

**Comment by stacktrust** [comment]
Comments added to JIRA ticket, https://openxt.atlassian.net/browse/OXT-384

**Comment by jctemkin** [comment]
Just a quick note before I head out for the night--commit 2cc73bc requires "yajl" to be added to the DEPENDS line in XCPMD's bitbake recipe; I'll PR this change shortly.

**Comment by rossphilipson** [comment]
I have reviewed the code the best I could and did a fair amount of testing with this feature. The problems I did find I reported to Jennifer and she has fixed them. The feature seems to be working as advertised. I am going to merge this tomorrow if there are no objections...

**Pull request merged**
