### PR TITLE
[xcpmd] Amend licenses.

### PR DESCRIPTION
**Pull request by jctemkin**
License and copyright corrections, some related to [OXT-390](https://openxt.atlassian.net/browse/OXT-390) and some not.

### CODE REVIEW

**Comment by jean-edouard** [comment]
+1

**Comment by cjp256** [comment]
LGTM

**Comment by jean-edouard** [comment]
This is good to merge. However, I don't want to introduce a conflict with the other PR, which is rather big.
I suggest we merge this after PR15

**Comment by rossphilipson** [comment]
This one is now conflicting - you will have to rebase it before we can merge it.

**Comment by jctemkin** [comment]
Rebased.

**Pull request merged**
